DROP TRIGGER IF EXISTS receipts_no_delete ON receipts;
DROP TRIGGER IF EXISTS payment_allocations_no_delete ON payment_allocations;
DROP TRIGGER IF EXISTS payments_no_delete ON payments;
DROP TRIGGER IF EXISTS invoice_lines_no_delete ON invoice_lines;
DROP TRIGGER IF EXISTS invoices_no_delete ON invoices;
DROP FUNCTION IF EXISTS prevent_financial_delete();
DROP TABLE IF EXISTS receipts;
DROP TABLE IF EXISTS payment_allocations;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS cash_shifts;
DROP TABLE IF EXISTS invoice_lines;
DROP TABLE IF EXISTS invoices;
DROP TABLE IF EXISTS provisioning_commands;
DROP TABLE IF EXISTS sync_conflicts;
DROP TABLE IF EXISTS sync_jobs;
DROP TABLE IF EXISTS pppoe_accounts;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS package_router_profiles;
DROP TABLE IF EXISTS package_prices;
DROP TABLE IF EXISTS packages;
DROP TABLE IF EXISTS ppp_profiles;
DROP TABLE IF EXISTS routers;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS tenant_counters;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_tenant_id_id_unique;
DROP TYPE IF EXISTS sync_status;
DROP TYPE IF EXISTS service_status;